Tela gerenciamento, funções
MATA63-UFBA-Gerenciamento-de-Labs/frontEnd pull request #21
Opened 2023-11-26 09:52 UTC by unknownFFr

Falta colocar os modais, mas pronto pra integração com o bakc eu acho

2023-11-26 15:49 UTC, iureguimaraes approved these changes

2023-11-27 22:21 UTC, Beckhauser1 approved these changes

2023-11-29 11:21 UTC, TiagoGSouza requested changes

2023-11-29 11:21 UTC, TiagoGSouza commented on pages/tela-aluno/index.jsx
> +        <Input type={"dropdown"} title={"Laboratório"} placeholder={"Selecione a laboratório"} value={lab1} onChange={(e) => setLab1(e.target.value)}key={3}/>
tem como adicionar um id para cada campo?

2023-11-29 11:21 UTC, TiagoGSouza commented on pages/tela-aluno/index.jsx
> +    var secondRow1 = [<Input type={"dropdown"} title={"Turma"} placeholder={"Selecione a turma"} value={turma1} onChange={(e) => setTurma1(e.target.value)}key={4}/>]
tem como adicionar um id?

2023-11-29 11:21 UTC, TiagoGSouza commented on pages/tela-aluno/index.jsx
>      var buttons1 = [
tem como adicionar um id para cada botão?

2023-11-29 11:21 UTC, TiagoGSouza commented on pages/tela-aluno/index.jsx
> +    var buttons2 = [
tem como adicionar um id para cada campo e button?

2023-11-29 11:21 UTC, TiagoGSouza commented on pages/tela-aluno/index.jsx
>          <Button
tem como adicionar um id para cada campo e button ?

2023-11-29 11:21 UTC, TiagoGSouza commented on pages/tela-professor/index.jsx
>      var actions = [
tem como adicionar um id para cada button?

2023-11-29 11:21 UTC, TiagoGSouza commented on pages/tela-tecnico/index.jsx
>      var actions = [
tem como adicionar um id para cada button?

2023-11-29 17:08 UTC, TiagoGSouza approved these changes

2023-11-30 22:02 UTC, merged